theme: jekyll-theme-cayman
title: NICE
description: "Luke Kenworthy<sup>1</sup>, Siddharth Nayak<sup>2</sup>, Christopher Chin<sup>2</sup>, Hamsa Balakrishnan<sup>2</sup> \
              \n\n <sup>1</sup>MIT, <sup>2</sup>USAF-MIT AI Accelerator"
