theme: jekyll-theme-cayman
title: NICE
description: |
            Luke Kenworthy<sup>1</sup>, Siddharth Nayak<sup>1</sup>, Christopher Chin<sup>1</sup>, Hamsa Balakrishnan<sup>1</sup>
            
            MIT, USAF-MIT AI Accelerator
